spring:
  main:
    banner-mode: off
  application:
    name: coin-catalog-mcp
  profiles:
    default: http
  ai:
    mcp:
      server:
        name: coin-catalog-mcp
        version: 0.1.0
        type: SYNC
        annotation-scanner:
          enabled: true

logging:
  file:
    name: logs/coin-catalog-mcp.log
